import Joi from "joi";

export const listing = Joi.object({
    number: Joi.number().required(),
    search: Joi.string().allow("").required(),
});

export const get = Joi.object({
    id: Joi.number().required(),
});

export const creation = Joi.object({
    name: Joi.string().max(200).required(),
    motherName: Joi.string().max(200).optional().allow(""),
    cpf: Joi.string().optional().allow(""),
    rg: Joi.string().optional().allow(""),
    rgIssuer: Joi.string().optional().allow(""),
    cep: Joi.string().optional().allow(""),
    uf: Joi.any().valid(
        "AC",
        "AL",
        "AP",
        "AM",
        "BA",
        "CE",
        "DF",
        "ES",
        "GO",
        "MA",
        "MS",
        "MT",
        "MG",
        "PA",
        "PB",
        "PR",
        "PE",
        "PI",
        "RJ",
        "RN",
        "RS",
        "RO",
        "RR",
        "SC",
        "SP",
        "SE",
        "TO"
    ),
    city: Joi.string().optional().allow(""),
    neighborhood: Joi.string().optional().allow(""),
    street: Joi.string().optional().allow(""),
    mail: Joi.string().optional().allow(""),
    phone: Joi.string().optional().allow(""),
    birthplace: Joi.string().optional().allow(""),
    profession: Joi.string().optional().allow(""),
    civil: Joi.string().valid("C", "V", "D", "S"),
    customerSince: Joi.date(),
    gender: Joi.string().valid("M", "F").required(),
    birthdate: Joi.date().required(),
    serie: Joi.string().optional().allow(""),
    ctps: Joi.string().optional().allow(""),
    numberFolder: Joi.string().optional().allow(""),
    pis: Joi.string().optional().allow(""),
    responsibleFolder: Joi.string().optional().allow(""),
    smartPhone: Joi.string().optional().allow(""),
    statusCustomer: Joi.string().valid("CONCLUIDO", "CANCELADO", "ANDAMENTO", "PARADO"),
    origin: Joi.string().valid("INDICACAO", "INSTAGRAM", "PARCERIA", "ANUNCIOS"),
    stateLife: Joi.string().valid("V", "F"),
    education: Joi.string().optional().allow(""),
    payment: Joi.bool().optional(),
    passwordINSS: Joi.string().optional().allow(""),
    imageProfile: Joi.string().optional().allow(""),
});

export const update = Joi.object({
    id: Joi.number().required(),
    name: Joi.string().max(200),
    motherName: Joi.string().max(200).optional().allow(""),
    cpf: Joi.string().optional().allow(""),
    rg: Joi.string().optional().allow(""),
    rgIssuer: Joi.string().optional().allow(""),
    cep: Joi.string().optional().allow(""),
    uf: Joi.any().valid(
        "AC",
        "AL",
        "AP",
        "AM",
        "BA",
        "CE",
        "DF",
        "ES",
        "GO",
        "MA",
        "MS",
        "MT",
        "MG",
        "PA",
        "PB",
        "PR",
        "PE",
        "PI",
        "RJ",
        "RN",
        "RS",
        "RO",
        "RR",
        "SC",
        "SP",
        "SE",
        "TO"
    ),
    city: Joi.string().optional().allow(""),
    neighborhood: Joi.string().optional().allow(""),
    street: Joi.string().optional().allow(""),
    mail: Joi.string().optional().allow(""),
    phone: Joi.string().optional().allow(""),
    birthplace: Joi.string().optional().allow(""),
    profession: Joi.string().optional().allow(""),
    civil: Joi.string().valid("C", "V", "D", "S"),
    customerSince: Joi.date(),
    gender: Joi.string().valid("M", "F").required(),
    birthdate: Joi.date(),
    serie: Joi.string().optional().allow(""),
    ctps: Joi.string().optional().allow(""),
    numberFolder: Joi.string().optional().allow(""),
    pis: Joi.string().optional().allow(""),
    responsibleFolder: Joi.string().optional().allow(""),
    smartPhone: Joi.string().optional().allow(""),
    statusCustomer: Joi.string().valid("CONCLUIDO", "CANCELADO", "ANDAMENTO", "PARADO"),
    origin: Joi.string().valid("INDICACAO", "INSTAGRAM", "PARCERIA", "ANUNCIOS"),
    stateLife: Joi.string().valid("V", "F"),
    education: Joi.string().optional().allow(""),
    payment: Joi.bool().optional(),
    passwordINSS: Joi.string().optional().allow(""),
    imageProfile: Joi.string().optional().allow(""),
});

export const deletion = Joi.object({
    id: Joi.number().required(),
});

